# Generated by Django 5.1.4 on 2025-04-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customusermodel_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='google_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
