# Generated by Django 5.1.4 on 2025-04-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customusermodel_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
