# Generated by Django 5.1.4 on 2025-04-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customusermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
